export const UPLOAD_HOUSE_REQUEST = 'UPLOAD_HOUSE_REQUEST';
export const UPLOAD_HOUSE_SUCCESS = 'UPLOAD_HOUSE_SUCCESS';
export const UPLOAD_HOUSE_FAIL = 'UPLOAD_HOUSE_FAIL';
export const UPLOAD_HOUSE_RESET = 'UPLOAD_HOUSE_RESET';

export const UPLOAD_PARLOR_IMAGE_REQUEST = 'UPLOAD_PARLOR_IMAGE_REQUEST';
export const UPLOAD_PARLOR_IMAGE_SUCCESS = 'UPLOAD_PARLOR_IMAGE_SUCCESS';
export const UPLOAD_PARLOR_IMAGE_FAIL = 'UPLOAD_PARLOR_IMAGE_FAIL';

export const UPLOAD_KITCHEN_IMAGE_REQUEST = 'UPLOAD_KITCHEN_IMAGE_REQUEST';
export const UPLOAD_KITCHEN_IMAGE_SUCCESS = 'UPLOAD_KITCHEN_IMAGE_SUCCESS';
export const UPLOAD_KITCHEN_IMAGE_FAIL = 'UPLOAD_KITCHEN_IMAGE_FAIL';

export const UPLOAD_TOILET_IMAGE_REQUEST = 'UPLOAD_TOILET_IMAGE_REQUEST';
export const UPLOAD_TOILET_IMAGE_SUCCESS = 'UPLOAD_TOILET_IMAGE_SUCCESS';
export const UPLOAD_TOILET_IMAGE_FAIL = 'UPLOAD_TOILET_IMAGE_FAIL';

export const UPLOAD_ROOM_IMAGE_REQUEST = 'UPLOAD_ROOM_IMAGE_REQUEST';
export const UPLOAD_ROOM_IMAGE_SUCCESS = 'UPLOAD_ROOM_IMAGE_SUCCESS';
export const UPLOAD_ROOM_IMAGE_FAIL = 'UPLOAD_ROOM_IMAGE_FAIL';

export const UPLOAD_BATH_ROOM_IMAGE_REQUEST = 'UPLOAD_BATH_ROOM_IMAGE_REQUEST';
export const UPLOAD_BATH_ROOM_IMAGE_SUCCESS = 'UPLOAD_BATH_ROOM_IMAGE_SUCCESS';
export const UPLOAD_BATH_ROOM_IMAGE_FAIL = 'UPLOAD_BATH_ROOM_IMAGE_FAIL';
