import { TableInterface } from './types';

export const tableValues = [
  {
    active: true,
    blocked: false,
    deActivated: false,
    // deleteIcon: '',
    email: 'nwankwoernest2020@gmail.com',
    fullName: 'Nwankwo Ernest Onyebuchi',
    image: '',
    position: 'Admin',
    startDate: '02-01-2023',
    location: 'Uyo',
    // upDateicon: '',
  },
  {
    active: false,
    blocked: true,
    deActivated: false,
    // deleteIcon: '',
    email: 'nwankwoernest2020@gmail.com',
    fullName: 'Nwankwo Ernest Onyebuchi',
    image: '',
    position: 'User',
    startDate: '02-01-2023',
    location: 'Ebonyi',
    // upDateicon: '',
  },
  {
    active: false,
    blocked: false,
    deActivated: true,
    // deleteIcon: '',
    email: 'nwankwoernest2020@gmail.com',
    fullName: 'Nwankwo Ernest Onyebuchi',
    image: '',
    position: 'User',
    startDate: '02-01-2023',
    location: 'Abia',
    // upDateicon: '',
  },
  {
    active: true,
    blocked: false,
    deActivated: false,
    // deleteIcon: '',
    email: 'nwankwoernest2020@gmail.com',
    fullName: 'Nwankwo Ernest Onyebuchi',
    image: '',
    position: 'User',
    startDate: '02-01-2023',
    location: 'Calaba',
    // upDateicon: '',
  },
  {
    active: false,
    blocked: true,
    deActivated: false,
    // deleteIcon: '',
    email: 'nwankwoernest2020@gmail.com',
    fullName: 'Nwankwo Ernest Onyebuchi',
    image: '',
    position: 'User',
    startDate: '02-01-2023',
    location: 'Jos',
    // upDateicon: '',
  },
  {
    active: false,
    blocked: false,
    deActivated: true,
    // deleteIcon: '',
    email: 'nwankwoernest2020@gmail.com',
    fullName: 'Nwankwo Ernest Onyebuchi',
    image: '',
    position: 'User',
    startDate: '02-01-2023',
    location: 'Enugu',
    // upDateicon: '',
  },
  {
    active: true,
    blocked: false,
    deActivated: false,
    // deleteIcon: '',
    email: 'nwankwoernest2020@gmail.com',
    fullName: 'Nwankwo Ernest Onyebuchi',
    image: '',
    position: 'User',
    startDate: '02-01-2023',
    location: 'Delta',
    // upDateicon: '',
  },
  {
    active: true,
    blocked: false,
    deActivated: false,
    // deleteIcon: '',
    email: 'nwankwoernest2020@gmail.com',
    fullName: 'Nwankwo Ernest Onyebuchi',
    image: '',
    position: 'User',
    startDate: '02-01-2023',
    location: 'Uyo',
    // upDateicon: '',
  },
  {
    active: true,
    blocked: false,
    deActivated: false,
    // deleteIcon: '',
    email: 'nwankwoernest2020@gmail.com',
    fullName: 'Nwankwo Ernest Onyebuchi',
    image: '',
    position: 'User',
    startDate: '02-01-2023',
    location: 'Lagos',
    // upDateicon: '',
  },
  {
    active: true,
    blocked: false,
    deActivated: false,
    // deleteIcon: '',
    email: 'nwankwoernest2020@gmail.com',
    fullName: 'Nwankwo Ernest Onyebuchi',
    image: '',
    position: 'User',
    startDate: '02-01-2023',
    location: 'Abuja',
    // upDateicon: '',
  },
  {
    active: false,
    blocked: false,
    deActivated: true,
    // deleteIcon: '',
    email: 'nwankwoernest2020@gmail.com',
    fullName: 'Nwankwo Ernest Onyebuchi',
    image: '',
    position: 'User',
    startDate: '02-01-2023',
    location: 'Kaduna',
    // upDateicon: '',
  },
  {
    active: true,
    blocked: false,
    deActivated: false,
    // deleteIcon: '',
    email: 'nwankwoernest2020@gmail.com',
    fullName: 'Nwankwo Ernest Onyebuchi',
    image: '',
    position: 'User',
    startDate: '02-01-2023',
    location: 'Gwombe',
    // upDateicon: '',
  },
  {
    active: false,
    blocked: true,
    deActivated: false,
    // deleteIcon: '',
    email: 'nwankwoernest2020@gmail.com',
    fullName: 'Nwankwo Ernest Onyebuchi',
    image: '',
    position: 'User',
    startDate: '02-01-2023',
    location: 'Ikotekpene',
    // upDateicon: '',
  },
];
