export const ACTIVATE_USER_REQUEST = 'ACTIVATE_USER_REQUEST';
export const ACTIVATE_USER_SUCCESS = 'ACTIVATE_USER_SUCCESS';
export const ACTIVATE_USER_FAIL = 'ACTIVATE_USER_FAIL';

export const EDIT_USER_RESET = 'EDIT_USER_RESET';

export const BLOCK_USER_REQUEST = 'BLOCK_USER_REQUEST';
export const BLOCK_USER_SUCCESS = 'BLOCK_USER_SUCCESS';
export const BLOCK_USER_FAIL = 'BLOCK_USER_FAIL';
export const RESET_USER = 'RESET_USER';

export const DE_ACTIVATE_USER_REQUEST = 'DE_ACTIVATE_USER_REQUEST';
export const DE_ACTIVATE_USER_SUCCESS = 'DE_ACTIVATE_USER_SUCCESS';
export const DE_ACTIVATE_USER_FAIL = 'DE_ACTIVATE_USER_FAIL';

export const PROMOTE_USER_REQUEST = 'PROMOTE_USER_REQUEST';
export const PROMOTE_USER_SUCCESS = 'PROMOTE_USER_SUCCESS';
export const PROMOTE_USER_FAIL = 'PROMOTE_USER_FAIL';

export const DEMOTE_USER_REQUEST = 'DEMOTE_USER_REQUEST';
export const DEMOTE_USER_SUCCESS = 'DEMOTE_USER_SUCCESS';
export const DEMOTE_USER_FAIL = 'DEMOTE_USER_FAIL';
