import { Favourite_img_1 } from '../../../../assets/images';
import { FavouriteInterface } from './types';

export const favouriteValues: Array<FavouriteInterface> = [
  {
    date: '20 November 2020',
    fit: '2 + 2',
    image: Favourite_img_1,
    meters: 50,
    numOfStirs: 3,
    price: 125,
    street: 'London Dean st',
    title: 'daily rental Apart',
  },
  {
    date: '20 November 2020',
    fit: '2 + 2',
    image: Favourite_img_1,
    meters: 50,
    numOfStirs: 3,
    price: 125,
    street: 'London Dean st',
    title: 'daily rental Apart',
  },
  {
    date: '20 November 2020',
    fit: '2 + 2',
    image: Favourite_img_1,
    meters: 50,
    numOfStirs: 3,
    price: 125,
    street: 'Manchester City',
    title: 'daily rental Apart',
  },
  {
    date: '20 November 2020',
    fit: '2 + 2',
    image: Favourite_img_1,
    meters: 50,
    numOfStirs: 3,
    price: 125,
    street: 'WestHam Londen',
    title: 'daily rental Apart',
  },
  {
    date: '20 November 2020',
    fit: '2 + 2',
    image: Favourite_img_1,
    meters: 50,
    numOfStirs: 3,
    price: 125,
    street: 'London Dean st',
    title: 'daily rental Apart',
  },
  {
    date: '20 November 2020',
    fit: '2 + 2',
    image: Favourite_img_1,
    meters: 50,
    numOfStirs: 3,
    price: 125,
    street: 'Paris France',
    title: 'daily rental Apart',
  },
  {
    date: '20 November 2020',
    fit: '2 + 2',
    image: Favourite_img_1,
    meters: 50,
    numOfStirs: 3,
    price: 125,
    street: 'Paris France',
    title: 'daily rental Apart',
  },
  {
    date: '20 November 2020',
    fit: '2 + 2',
    image: Favourite_img_1,
    meters: 50,
    numOfStirs: 3,
    price: 125,
    street: 'Paris France',
    title: 'daily rental Apart',
  },
  {
    date: '20 November 2020',
    fit: '2 + 2',
    image: Favourite_img_1,
    meters: 50,
    numOfStirs: 3,
    price: 125,
    street: 'Paris France',
    title: 'daily rental Apart',
  },
  {
    date: '20 November 2020',
    fit: '2 + 2',
    image: Favourite_img_1,
    meters: 50,
    numOfStirs: 3,
    price: 125,
    street: 'Paris France',
    title: 'daily rental Apart',
  },
  {
    date: '20 November 2020',
    fit: '2 + 2',
    image: Favourite_img_1,
    meters: 50,
    numOfStirs: 3,
    price: 125,
    street: 'Paris France',
    title: 'daily rental Apart',
  },
  {
    date: '20 November 2020',
    fit: '2 + 2',
    image: Favourite_img_1,
    meters: 50,
    numOfStirs: 3,
    price: 125,
    street: 'Paris France',
    title: 'daily rental Apart',
  },
  {
    date: '20 November 2020',
    fit: '2 + 2',
    image: Favourite_img_1,
    meters: 50,
    numOfStirs: 3,
    price: 125,
    street: 'Paris France',
    title: 'daily rental Apart',
  },
  {
    date: '20 November 2020',
    fit: '2 + 2',
    image: Favourite_img_1,
    meters: 50,
    numOfStirs: 3,
    price: 125,
    street: 'Paris France',
    title: 'daily rental Apart',
  },
  {
    date: '20 November 2020',
    fit: '2 + 2',
    image: Favourite_img_1,
    meters: 50,
    numOfStirs: 3,
    price: 125,
    street: 'Paris France',
    title: 'daily rental Apart',
  },
  {
    date: '20 November 2020',
    fit: '2 + 2',
    image: Favourite_img_1,
    meters: 50,
    numOfStirs: 3,
    price: 125,
    street: 'Paris France',
    title: 'daily rental Apart',
  },
];
