// LOCATION MANAGEMENT
export const CREATE_REGION_REQUEST = 'CREATE_REGION_REQUEST';
export const CREATE_REGION_SUCCESS = 'CREATE_REGION_SUCCESS';
export const CREATE_REGION_FAIL = 'CREATE_REGION_FAIL';

export const RESET_STATE = 'RESET_STATE';

export const GET_ALL_REGION_REQUEST = 'GET_ALL_REGION_REQUEST';
export const GET_ALL_REGION_SUCCESS = 'GET_ALL_REGION_SUCCESS';
export const GET_ALL_REGION_FAIL = 'GET_ALL_REGION_FAIL';

export const ADD_STATE_REQUEST = 'ADD_STATE_REQUEST';
export const ADD_STATE_SUCCESS = 'ADD_STATE_SUCCESS';
export const ADD_STATE_FAIL = 'ADD_STATE_FAIL';

export const DELETE_STATE_REQUEST = 'DELETE_STATE_REQUEST';
export const DELETE_STATE_SUCCESS = 'DELETE_STATE_SUCCESS';
export const DELETE_STATE_FAIL = 'DELETE_STATE_FAIL';
export const RESET_DELETE_STATE = 'RESET_DELETE_STATE';

export const ADD_LOCAL_GOV_REQUEST = 'ADD_LOCAL_GOV_REQUEST';
export const ADD_LOCAL_GOV_SUCCESS = 'ADD_LOCAL_GOV_SUCCESS';
export const ADD_LOCAL_GOV_FAIL = 'ADD_LOCAL_GOV_FAIL';
export const RESET_ADD_LOCAL_GOV = 'RESET_ADD_LOCAL_GOV';
